### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by KeironO** [KeironO/DIMEdb#2]
# DIMEdb Roadmap November 2017
A summary of our plans and goals.

- [ ] Version 1.0 of the database to be finalised.
- [x] JCAMP and TSV export of data from metabolite page
- [ ] JCAMP dumps of the entire database, readily available for download.
- [ ] Over-representation analysis of KEGG pathways for a given Metabolite Table.
- [ ] Possible reintroduction of the MetaboliteClipboard.
- [ ] Solidifying of the front end, providing Metabolite views through server-side.
- [ ] Conversion from JavaScript to AngularJS.
- [ ] Simpler API access, needs consideration.

**Comment by KeironO** [comment]
## Database Version 1.0

As it stands, the decision has been made to dispose both CHEBI and PubChem in their entirety, mainly due to the confusion surrounding what exactly constitutes an organic compound. Instead, DIMEdb will integrate the following publicly available databases:

- Spektraris
- GOLM
- Respect
- HMDB
- NMRShiftDB
- MassBank

Moreover, there have been multiple requests for Reactome pathways to be included. This will be considered.

**Comment by KeironO** [comment]
## Simpler API access

A couple comments regarding the API has made me realise that there are some 'common' types of queries that are made that don't require full access to the mongo-esque interface.
